name: veremisfit
channels:
  - conda-forge
  - defaults
  - http://ssb.stsci.edu/astroconda
dependencies:
  - astropy=4.3.1
  - bokeh=2.0.2
  - ipython=7.31.1
  - lmfit=1.0.3
  - matplotlib=3.5.2
  - numpy=1.21.5
  - pandas=1.3.5
  - requests=2.32.3
  - scipy=1.7.3
  - termcolor=2.4.0
  - pip
  - pip:
      - jinja2==2.11.3
      - markupsafe==2.0.1
      - ttkbootstrap==1.10.1